### ISSUE TITLE
[device-port] [flo] Nexus 7 2013 Wifi

### ISSUE THREAD

**Issue by thomasloubejac** [Halium/projectmanagement#104]
Tree: 

- [ ] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by doniks** [comment]
@thomasloubejac how is this issue going? I'd assume you could mostly use the deb port

**Comment by doniks** [comment]
no response for more than a month. It makes no sense to keep an inactive AND empty issue around

**Comment by thomasloubejac** [comment]
Oh sorry I forgot
You did well

Happy winter
Thomas
