### ISSUE TITLE
[device-port][sm-g610m] ubuntu touch for j7 prime

### ISSUE THREAD

**Issue by l3eksz** [Halium/projectmanagement#110]
I love so much the Linux Ubuntu, it i'll be nice use Ubuntu Touch in J7 Prime (Sorry for my bad english)

**Comment by jbruechert** [comment]
FYI Halium is not only about porting Ubuntu Touch, so please don't include ubuntu Touch in the name of this issue. If you already started working on it, please use the issue template used in the other issues

**Comment by doniks** [comment]
doesn't seem like any actual porting is going on here
