### ISSUE TITLE
[device-port] [golden] Samsung Galaxy S3 mini

### ISSUE THREAD

**Issue by ghost** [Halium/projectmanagement#114]
Please start from scratch

**Comment by gautam142857** [comment]
Would the steps be same for a Samsung Galaxy s3. I have one which I can use and we can collaborate.

**Comment by doniks** [comment]
dpaste link is dead. please share your manifest

**Comment by ghost** [comment]
I'm sorry I don't have it anymore

**Comment by doniks** [comment]
too bad :(
