### ISSUE TITLE
[device-port] [zerofltexx] Samsung Galaxy S6

### ISSUE THREAD

**Issue by Paktosan** [Halium/projectmanagement#116]
Tree: halium-7.1

- [x] Create manifest (to be uploaded)
- [x] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by xkazumo** [comment]
i´m with you m8. if you need someone to test the rom message me!
my s6 zerofltexx is waiting ;D

**Comment by Paktosan** [comment]
I am currently struggling with booting the rootfs, but I think I am close. Probably should upload my progress.

**Comment by xkazumo** [comment]
If i can help just say it. Im running Debian on my PC, custom recovery on my phone etc.

**Comment by adcomp** [comment]
Waiting too .. already tried to do it myself but I'm stuck at "breakfast". I suspect something wrong with my  manifest.

**Comment by Tegner08** [comment]
Hey if you upload your progress I'd love to see if I can help.

**Comment by doniks** [comment]
if you, (or someone else!) has a manifest please reopen (or maybe just create a new issue) and do link the manifest!

**Comment by Saphar** [comment]
@Paktosan do you have any progress on this? I managed to build the kernel and systemimage but I am not able to boot into it, I get stuck with the message "Kernel is not SEANDROID enforcing"

**Comment by Paktosan** [comment]
I am sorry, but I neither have the phone or the PC I used back then anymore.
But I was also stuck booting so I do not have anything of value for you.

Am 08.02.21 um 11:51 schrieb Saphar:
