### ISSUE TITLE
[device-port] [chef] Motorola One Power 

### ISSUE THREAD

**Issue by rkssomayaji** [Halium/projectmanagement#126]
Tree: halium-7.1

- [ ] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by doniks** [comment]
no manifest. I'm closing this here. Feel free to reopen or make a new issue when there is a manifest
