### ISSUE TITLE
[device-port] [taimen] Google Pixel 2 XL

### ISSUE THREAD

**Issue by emolution11** [Halium/projectmanagement#127]
Tree: 

- [x] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by DrNohWon** [comment]
I am currently trying to port to the Pixel(Sailfish)

**Comment by Rudi9719** [comment]
Is there any progress/interest in this? @TonyKuroi and I are interested in working on it as well as getting an Android 8+ port going should make it easier to port moving forward due to project treble.

**Comment by emolution11** [comment]
halium based on 7.1.1 and taimen was released with 8.0 treble structure is
incompatible but you know that...haven't seen any progress, and I've been
busy I may just initialize my research again

**Comment by jalcine** [comment]
That'd be dope - I've been hoping and attempting to build this myselef.

**Comment by doniks** [comment]
if you have a manifest please reopen and link it
