### ISSUE TITLE
[device-port][Jasmine]Xiaomi Mi A2

### ISSUE THREAD

**Issue by ghost** [Halium/projectmanagement#132]
Requesting port for Xiaomi Mi A2

**Comment by lnjX** [comment]
You can't request a port here. Either do it yourself or ask someone who owns a device.

**Comment by mathieujobin** [comment]
Can we keep this open for collaboration nonetheless? 

I have a device and I am interested as well. but it would be my first port...

**Comment by doniks** [comment]
> Can we keep this open for collaboration nonetheless?
> 

Once you start the port, feel free to open a new issue. Issues with active porting going on, no matter how early stage are very welcome! Purely passive request aren't really useful.

> I have a device and I am interested as well. but it would be my first port...

Not to worry. Almost all ports are someone's first port. Start at docs.halium.org , join the tg/irc/matrix and give your port a shot!

**Comment by mathieujobin** [comment]
Thanks @doniks I'm on tg

I did created a manifest file and tried to build it

https://github.com/mathieujobin/halium-devices/commit/f55568a720ad944a2d348b1de47cd0d121cc42fc


my blocker seems to be the the proprietary elements were taken down by DMCA
https://github.com/TheMuppets/proprietary_vendor_xiaomi

is there anything that replaces this?

is it possible to start from kernel source?

https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/jasmine-o-oss

anyone could help, would be greatly appreciated

**Comment by doniks** [comment]
I see. That's a problem. It might be a showstopper down the road...

Maybe you can find another repo or ask in halium chat, or, I guess, you have all these blobs when you install android. They're inside. You should be able copy them out. 

However, (I am not a lawyer), you are prob not allowed to give it to anyone else! But you can use them yourself.

**Comment by likeadragonmaid** [comment]
@mathieujobin I am using https://github.com/shoukolate/android_vendor_xiaomi_sdm660-common and https://github.com/shoukolate/android_device_xiaomi_wayne vendors for MI A2 for building LineageOS 17.1. They might be useful for you.

**Comment by mathieujobin** [comment]
Oh @shoukolate thank you so much

How far did you get? Does it run nicely?

**Comment by likeadragonmaid** [comment]
I have only built LineageOS and everything works on it

**Comment by mathieujobin** [comment]
maybe it would be value to others if you could publish the build somewhere

**Comment by likeadragonmaid** [comment]
@mathieujobin https://forum.xda-developers.com/mi-a2/development/10-x-lineage-17-0-jasminesprout-t3966643

**Comment by shoukolate** [comment]
https://github.com/halium-xiaomi-sdm660/android_kernel_xiaomi_sdm660
