### ISSUE TITLE
[device-port] [eva] Huawei P9

### ISSUE THREAD

**Issue by kcxt** [Halium/projectmanagement#133]
Tree: 

- [X] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by weboose** [comment]
Hi, have you made some progress?

**Comment by kcxt** [comment]
> Hi, have you made some progress?

Hey! Sorry for the late reply. I've moved on to porting Sailfish as I think it suits my use cases better. My P9 is non-functional right now however if I get it going again I'll be porting Sailfish to it!

Closed as won't be working on this anytime soon.

**Comment by weboose** [comment]
> > Hi, have you made some progress?
> 
> Hey! Sorry for the late reply. I've moved on to porting Sailfish as I think it suits my use cases better. My P9 is non-functional right now however if I get it going again I'll be porting Sailfish to it!
> 
> Closed as won't be working on this anytime soon.

:)  Good luck

**Comment by weboose** [comment]
> > Hi, have you made some progress?
> 
> Hey! Sorry for the late reply. I've moved on to porting Sailfish as I think it suits my use cases better. My P9 is non-functional right now however if I get it going again I'll be porting Sailfish to it!
> 
> Closed as won't be working on this anytime soon.

I tried to make hybris-boot for p9, but usb didn't work, do you have this situation?

**Comment by kcxt** [comment]
> > > Hi, have you made some progress?
> > 
> > 
> > Hey! Sorry for the late reply. I've moved on to porting Sailfish as I think it suits my use cases better. My P9 is non-functional right now however if I get it going again I'll be porting Sailfish to it!
> > Closed as won't be working on this anytime soon.
> 
> I tried to make hybris-boot for p9, but usb didn't work, do you have this situation?

When I tried to port Sailfish (Before I broke my phone...), sending any packets to the device would cause a reboot, ping, ssh, telnet all caused it. However it did give me an IP Address.

I never got around to debugging properly however once you have working fixup mountpoints (The existing ones for eva are for Marshmallow and don't work) you can get a log file.

You can modify the init-debug script and try grabbing dmesg, you might be able to find out why gadget mode is broken.

Additionally, eva is confused and can't decide whether to load gadget mode through the android_usb driver or the configfs driver, I think this is the cause of the issue and it can be fixed by changing the kernel config options.

**Comment by weboose** [comment]
> > > > Hi, have you made some progress?
> > > 
> > > 
> > > Hey! Sorry for the late reply. I've moved on to porting Sailfish as I think it suits my use cases better. My P9 is non-functional right now however if I get it going again I'll be porting Sailfish to it!
> > > Closed as won't be working on this anytime soon.
> > 
> > 
> > I tried to make hybris-boot for p9, but usb didn't work, do you have this situation?
> 
> When I tried to port Sailfish (Before I broke my phone...), sending any packets to the device would cause a reboot, ping, ssh, telnet all caused it. However it did give me an IP Address.
> 
> I never got around to debugging properly however once you have working fixup mountpoints (The existing ones for eva are for Marshmallow and don't work) you can get a log file.
> 
> You can modify the init-debug script and try grabbing dmesg, you might be able to find out why gadget mode is broken.
> 
> Additionally, eva is confused and can't decide whether to load gadget mode through the android_usb driver or the configfs driver, I think this is the cause of the issue and it can be fixed by changing the kernel config options.

Thank you, since configfs can't work, now I have given up on porting halium.
