### ISSUE TITLE
[device-port] [X6] Nokia 6.1 Plus

### ISSUE THREAD

**Issue by krshnn** [Halium/projectmanagement#134]
Tree: 

- [ ] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by isubhampadhi56** [comment]
I want to test it.

**Comment by theglen35** [comment]
Hello are you still working on this? can you share it so i could continue your work?

**Comment by doniks** [comment]
if you have a manifest, please reopen and link it
