### ISSUE TITLE
[device port] [gtaxlwifi] port to Samsung Galaxy Tab A6 2016 (Wifi Only version)

### ISSUE THREAD

**Issue by slimjimsoftware** [Halium/projectmanagement#136]
Tree: 

- [x] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by fastbootfinesse** [comment]
im game ! :]

**Comment by doniks** [comment]
if you have a manifest, please reopen and link it
