### ISSUE TITLE
[bullhead] Re-enable the pm-service if required.

### ISSUE THREAD

**Issue by bhush9** [Halium/projectmanagement#14]
Currently we have following in init.bullhead.rc to disable the pm-service, 

```
@@ -292,6 +292,7 @@ service per_mgr /system/bin/pm-service
     class core
     user system
     group system net_raw
+    disabled
 
```

as otherwise if enabled, it results in following spam in dmesg and ultimately kernel panic

```
[ 79.686566] IPC_RTR: msm_ipc_router_bind: pm-service Do not have permissions
```

Investigate if pm-service is something essential or not and enable/disable it as needed.

**Comment by shadeslayer** [comment]
Apparently this is the power management service.

**Comment by bhush9** [comment]
Fixed with patches in kernel.. This needs to be enabled to get modem to boot up.

https://github.com/Halium/android_kernel_lge_bullhead/compare/a34bb3a905...0b64b0cd08

**Comment by z3ntu** [comment]
Link the required patches somewhere please (Porting guide probably) if you haven't already.

**Comment by bhush9** [comment]
Yes, I do plan to include those in porting guide..
