### ISSUE TITLE
[proposal] define the scope of the Halium project concretely

### ISSUE THREAD

**Issue by peat-psuwit** [Halium/projectmanagement#146]
As it currently is, Halium's scope seems to be unclear. Thus, I would like to define it as such:

-------------------

Halium's scope primarily consists of 2 parts.

1. Halium's Android is a minimal Android distribution designed to run within an LXC container. It will provide a set of interfaces to let the host of LXC container utilize Android's HAL to communicate with the hardware of Android-based smartphones. These interfaces come in 3 forms:
    1. Native Android interfaces. (e.g. rild's socket, Audio HAL (dlopen'ed directly), (original) WiFi HAL (a standard libhybris wrapper))
    2. Libhybris compat layer. Usually used to wrap Android C++ interfaces, contains some logic, and has its counter-part compiled in the Android tree. (e.g. HWC2 compat layer)
    3. Custom interfaces. This will contain more than a compat layer and may have quite deep integration within Android code. (e.g. camera interfaces, which consists of camera compat layer , custom media compat layer, and a deep modification of Android's libmedia). If possible, we would like to reduce this kind of interface as much as possible to reduce our workload, especially those doing deep modification to Android.
2. Halium's middleware is a set of software/libraries/modules on GNU/Linux which talks to the interfaces in 1. and is distro- & toolkit-agnostic enough. For example, this includes pulseaudio-module-droid and oFono, but will not include qtubuntu-camera (a client of the aforementioned camera interface, because it's tied to Qt). Halium might not be upstream of most of the middlewares. Thus, most of the time we'll just maintain the minimal patch(es) that make them work in Halium-based environment.

Halium will primarily be a source-only distribution. Downstream distributions (such as Plasma Mobile or Ubuntu Touch) can place some modification into the Android part (for example, Ubuntu Touch's platform-api, additional kernel cmdline to enable AppArmor, or another initramfs). Then, they can build & distribute Halium as part of the distribution.

Halium will provide the reference rootfs to demonstrate how to integrate Halium into distributions and helps porters in developing their port. It'll contain the common middlewares and enough testing tools to help determine if the port is likely to work in more full-blown distributions or not. A reference repo, which is primarily used to build the reference rootfs, will also be provided. Downstream distributions can use this repo but are not required to.

------------------------------

This still leaves a few questions (__Edit:__ All these questions are answered. See comment 2.):
1. Should deployment, initramfs and convention on how files are placed be part of Halium? Currently, it seems like all OSes that use Halium roll their own approaches on this. I don't know how people think about this, but I guess we can leave them out of Halium.
2. ~~Should Halium provides pre-built images, or distribution should build them themselves?~~ @bhush9 said no. See comment.
3. Do we have to define kernel interfaces? How to handle conflicting kernel requirements like AppArmor requirement on Ubuntu Touch? (very likely we'll leave it enabled, but requires kernel cmdline to enable it. This probably requires such distro to build the boot image themselves.)
4. I supposed that with @bhush9's comment, it seems like the images for "supported devices" (for a distribution) is distributed by that distribution. But what about the unofficial devices? How should it be distributed & install? Distribution-dependent?
5. What about the distribution of Halium's middleware? Currently, it seems like Halium is providing the repo at http://repo.halium.org/, but Plasma Mobile is the only distribution using it. Personally, I believe they should be source-only too, and then downstream distribution should compile and provide them in their repo/image. (Packaging effort might be shared between e.g. Plasma Mobile & Ubuntu Touch (as they are both Ubuntu/Debian-based), but each distribution still should build packages on their own). Maybe the repo should live on, but only for reference rootfs? (and now should reference rootfs be part of Halium's scope?)

**Comment by peat-psuwit** [comment]
> 2. Should Halium provides pre-built images, or distribution should build them themselves?

On this, @bhush9 has said on Telegram that:

> In general, everything binary should be handled by the distribution. Halium itself can provide reference system but not final distribution

I'll update the issue accordingly.

**Comment by bhush9** [comment]
To answer questions,

1. They're not scope of Halium, no. They're largely part of the how distribution wants to implement it, halium-boot is recommended solution but distro may as well use the hybris-boot or use something else taking reference rootfs as example.

2. I've answered.

3. Your proposal there makes sense.

4. Yes. Distribution dependent, as different distro might have different OTA update/upgrade/install methods it is quite messy for Halium to handle it

5. repo.halium.org is used as reference yes, although to avoid rebuilds plasma mobile is just re-using it as-is, since we don't have any distribution specific middleware changes.

**Comment by peat-psuwit** [comment]
Based on @bhush9's answers and additional discussions in the Telegram group. I've updated the proposal again. If consensus is reached, I'll update the Halium's website to contain this, and we can consider this closed.
