### ISSUE TITLE
[device port] [beryllium] Port to Pocophone F1

### ISSUE THREAD

**Issue by TejasSriv** [Halium/projectmanagement#149]
Tree: 

- [x] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by doniks** [comment]
please link your manifest

**Comment by TejasSriv** [comment]
I think halium project is only for devices that have support for LOS 14, but since POCO F1 does not have LOS 14 support so I could not create a complete manifest file.

**Comment by doniks** [comment]
ok. too bad :(
