### ISSUE TITLE
[device-port][chagalllte] Galaxy Tab S 10.5 LTE

### ISSUE THREAD

**Issue by 4soobs** [Halium/projectmanagement#159]
Tree:  halium-7.1

### **Test tree**
----------------------------------

- [x] Create manifest 
- [x] Boot image and system image build successfully
- [x] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [x] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [x] test_vibrator
  * [x] test_wifi `Partially works. Device finds Wi-Fi networks, tho cannot ping.`
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] ~~test_nfc~~ `chagalllte has no NFC functionality.`
  * [ ] test_recorder

**Comment by doniks** [comment]
If you have the manifest then please do link it

**Comment by 4soobs** [comment]
> If you have the manifest then please do link it

Hello, I apologize for that. I wanted to create a manifest and link it, but for now I am having some issues now. I will try creating a repo and linking as soon as I can.

**Comment by 4soobs** [comment]
> If you have the manifest then please do link it

Do you have this device and would like to help me? Currently I am encountering an "KERNEL IS NOT SEANDROID ENFORCING",

**Comment by doniks** [comment]
Hi @rlucins ok. No worries. Whenever you have it. Good luck with the port!

No, I do not have that device, sorry, can't help you there. Not sure what exactly this is error is. Seems to be a Samsung thing. Maybe it's not even a real problem ... Btw, you are aware of the irc/matrix/telegram chat right? https://docs.halium.org/en/latest/porting/first-steps.html You're gonna get best and fasted help there

**Comment by 4soobs** [comment]
> Hi @rlucins ok. No worries. Whenever you have it. Good luck with the port!
> 
> No, I do not have that device, sorry, can't help you there. Not sure what exactly this is error is. Seems to be a Samsung thing. Maybe it's not even a real problem ... Btw, you are aware of the irc/matrix/telegram chat right? https://docs.halium.org/en/latest/porting/first-steps.html You're gonna get best and fasted help there

That is ok. I do know that there is an irc/matrix/telegram chat. I couldn't seem to find their chat on Telegram.
