### ISSUE TITLE
[issue] A "PREEMPT" error on Samsung Galaxy Tab S 10.5, (chagalllte)

### ISSUE THREAD

**Issue by 4soobs** [Halium/projectmanagement#160]
For a whole day, I have been hitting this brick wall, trying to fix it, and didn't succeed. Here is the wall I am having here: "`Internal error: Oops - BUG: 0 [#1] PREEMPT SMP ARM`" Google didn't seem to help, since there are alot of threads, but no genuine answers. Please let me know if you have figured out this puzzle. Here is the full log of the `last_kmesg`: https://pastebin.com/1eEkUMrK

**Comment by doniks** [comment]
@rlucins a separate issue in github for a problem with one individual port doesn't really make sense. I'm closing this one
