### ISSUE TITLE
 [device-port][addison] Port to Moto z play (xt1635) 

### ISSUE THREAD

**Issue by joe-relax** [Halium/projectmanagement#162]
Tree: 

- [x] Create manifest 
- [x] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by doniks** [comment]
please link the manifest

**Comment by doniks** [comment]
no response. I'm closing this here. Feel free to reopen or make a new one when there is a manifest
