### ISSUE TITLE
[device-port] [] LG Stylo 2 Plus

### ISSUE THREAD

**Issue by ghost** [Halium/projectmanagement#163]
Tree: 

- [x] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

I have changed vendor files, kernel files, and correctly written out the manifest.xml for the ph2n device, but still gets stuck on "[ 96% 123/127] Building Kernel", the log can be found here ---> https://pastebin.com/Q1j0Ad1G

Could someone please help, and possibly tell me what I am doing wrong?

**Comment by ghost** [comment]
If you need any other information as well, please let me know!

**Comment by doniks** [comment]
123/127 looks weird but I can't see any errors in the log. Have you tried flashing it anyway?

**Comment by jbruechert** [comment]
The Building Kernel step takes some time and doesn't display any progress. How long have you waited for it to finish?

**Comment by ghost** [comment]
> 123/127 looks weird but I can't see any errors in the log. Have you tried flashing it anyway?

I can't, it doesn't show any IMG files..

**Comment by ghost** [comment]
> The Building Kernel step takes some time and doesn't display any progress. How long have you waited for it to finish?

Almost an hour, but it has been faster on other device tryhard ports that I tried to do and failed

**Comment by doniks** [comment]
@WolfLink115-Porting are you still working on this? I'd say at least having a manifest is the minimum to have an issue. Even if it doesn't build, it would show others what doesn't work and avoid wasting effort.

**Comment by ghost** [comment]
I kinda stopped working on it..

**Comment by doniks** [comment]
I see. Thanks for the response. Without activity AND without manifiest ... I'm closing this
