### ISSUE TITLE
[device-port] [falcon] Moto G

### ISSUE THREAD

**Issue by benclarkk** [Halium/projectmanagement#170]
yes
Tree: halium-7.1

- [x] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by doniks** [comment]
please link the manifest

**Comment by doniks** [comment]
actually, I see there is an issue for falcon already. Please collaborate over there: #77
