### ISSUE TITLE
[Device-Port] LG G Stylo

### ISSUE THREAD

**Issue by ghost** [Halium/projectmanagement#189]
Tree: 

- [x] Create manifest 
- [x] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

I am having issues with the step "mka halium-boot" it is the same error as the other port i tried to do, building kernel config. And I am sorry if this is a noob question, but what exactly is the manifest i keep hearing about?

**Comment by ghost** [comment]
https://pastebin.com/yFtiyNKE

Log file of what is in the Terminal when it fails...

**Comment by ghost** [comment]
OK, so with a bit more troubleshooting, i got halium-boot.img to build successfully. now im stuck on the build systemimage pary, it fails saying slim_daemon file wasn't found in the vendor directory, have i gotten the wrong blobs?

**Comment by ghost** [comment]
ok, now with a bit more changes, i got halium-boot and systemimage built successfully. now it is just a matter of debugging and getting it to boot operating systems!

**Comment by doniks** [comment]
Why did you close it? Also could you please make a PR to share your manifest http://docs.halium.org/en/latest/porting/get-sources.html#document

**Comment by ghost** [comment]
I don't know what a manifest is, wait.. Don't you mean the xml file that fetches the repo files?
edit: how to create a pull request also?

edit 1: https://github.com/Halium/halium-devices/pull/209/commits/4342840b94ef2217661a91534317f3df1ac3efc9   pull request

**Comment by ghost** [comment]
anyone??

**Comment by ghost** [comment]
@doniks

**Comment by doniks** [comment]
hey. yep that xml. that xml was the reason why you ticked the "manifest" box in your checklist, right ;) Seems you also figured out the PR. Thanks!

**Comment by WolfLink115** [comment]
Hey, could someone remove this pull request, this was my old account, and I do not have this specific device anymore.
