### ISSUE TITLE
[Device Port] LG W5

### ISSUE THREAD

**Issue by WolfLink115-Porting** [Halium/projectmanagement#194]
Tree: 

- [x] Create manifest 
- [x] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

Doesn't boot rootfs. need help fixing..

**Comment by WolfLink115-Porting** [comment]
Lost access to device, Closed.

**Comment by Mek101** [comment]
Sources? I happen to have access to the phone (although with a broken fastboot)
