### ISSUE TITLE
[device-port] [mata] Essential PH-1

### ISSUE THREAD

**Issue by alfonsojon** [Halium/projectmanagement#196]
Tree: halium-7.1

- [x] [Create manifest](https://github.com/Halium/halium-devices/pull/230) 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by alfonsojon** [comment]
Was successful in building the hybris-boot image, but building the system image is failing with 
```
Starting build with ninja
ninja: Entering directory `.'
ninja: error: 'vendor/essential/mata/proprietary/lib64/libril.so', needed by '/home/alfonsojon/android/halium/out/target/product/mata/system/lib64/libril.so', missing and no known rule to make it
make: *** [build/core/ninja.mk:152: ninja_wrapper] Error 1
make: Leaving directory '/home/alfonsojon/android/halium'

#### make failed to build some targets (10 seconds) ####
```

I checked [TheMuppets repo](https://github.com/TheMuppets/proprietary_vendor_essential/tree/cm-14.1/mata/proprietary/vendor/lib64) and found it does not, in fact, provide libril.so. Not sure where to go from here.

**Comment by doniks** [comment]
There is already a mata port going on here: https://github.com/Halium/projectmanagement/issues/122 please collaborate in that issue. The guys there might have an answer to your build problem
