### ISSUE TITLE
[device-port] [j5lte] [Halium-9.0] Samsung Galaxy J5 2015

### ISSUE THREAD

**Issue by uotlaf** [Halium/projectmanagement#198]
Tree:  Halium 9

- [x] Create manifest 
- [x] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_recorder

Kernel config made by check-kernel-config -w results in an kernel panic. 
I will make manually an new .config

**Comment by uotlaf** [comment]
CONFIG_SYSVIPC
CONFIG_VT
CONFIG_MODULES
CONFIG_DEVTMPFS
CONFIG_DEVTMPFS_MOUNT
CONFIG_AUTOFS4_FS
causes kernel panic/ device not boots. I will try implement pstore and ramoops in this kernel.

**Comment by enesutku07** [comment]
open system? please ı use j5lte. but dont use ubports.

**Comment by nergzd723** [comment]
> CONFIG_SYSVIPC
> CONFIG_VT
> CONFIG_MODULES
> CONFIG_DEVTMPFS
> CONFIG_DEVTMPFS_MOUNT
> CONFIG_AUTOFS4_FS
> causes kernel panic/ device not boots. I will try implement pstore and ramoops in this kernel.

I've got halium-boot to work on j53gxx

**Comment by nergzd723** [comment]
@foreign-dev I got it to boot to UBPorts shell, it displays GNU/Linux Device. However, lxc does crash

**Comment by uotlaf** [comment]
> @foreign-dev I got it to boot to UBPorts shell, it displays GNU/Linux Device. However, lxc does crash
On j5lte?

**Comment by uotlaf** [comment]
> > CONFIG_SYSVIPC
> > CONFIG_VT
> > CONFIG_MODULES
> > CONFIG_DEVTMPFS
> > CONFIG_DEVTMPFS_MOUNT
> > CONFIG_AUTOFS4_FS
> > causes kernel panic/ device not boots. I will try implement pstore and ramoops in this kernel.
> 
> I've got halium-boot to work on j53gxx

CONFIG_SYSVIPC don't crash?
which kernel tree?

**Comment by uotlaf** [comment]
> open system? please ı use j5lte. but dont use ubports.

yes, j5lte
halium only.

**Comment by nergzd723** [comment]
> > > CONFIG_SYSVIPC
> > > CONFIG_VT
> > > CONFIG_MODULES
> > > CONFIG_DEVTMPFS
> > > CONFIG_DEVTMPFS_MOUNT
> > > CONFIG_AUTOFS4_FS
> > > causes kernel panic/ device not boots. I will try implement pstore and ramoops in this kernel.
> > 
> > 
> > I've got halium-boot to work on j53gxx
> 
> CONFIG_SYSVIPC don't crash?
> which kernel tree?

j53g, https://github.com/Galaxy-MSM8916/android_kernel_samsung_msm8916 this one. I sort of halted work on Halium for now since device is mainlined.

**Comment by nergzd723** [comment]
it also needs a lot of things to be patched, so I can't provide manifest rn

**Comment by uotlaf** [comment]
> it also needs a lot of things to be patched, so I can't provide manifest rn

This is what I used. but some configs result in a kernel panic
It also doesn't support pstore/ramoops, so the only way to debug is uart

what patches did you use?
