### ISSUE TITLE
[Device-Port] [ph2n] LG Stylo 2 Plus

### ISSUE THREAD

**Issue by WolfLink115** [Halium/projectmanagement#217]
Tree: 

- [x] Create manifest 
- [x] Boot image and system image build successfully
- [x] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [x] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

I need help getting the home menu to stop crashing after setup wizard. I already have it booting and into the GUI.

**Comment by WolfLink115** [comment]
UPDATE!! Booted into Home Screen!
working on configuring some buttons and hardware. need some help with that..

**Comment by bscheith** [comment]
Were you ever able to complete this?

**Comment by WolfLink115** [comment]
@bscheith I got the phone to boot and managed to watch youtube and some other stuff. I lost the phone somehow, and was never able to find it. I forgot to close this and say what happened. I am sorry for the confusion. There were some problems with it as far as I know, but I couldn't fix them. Sorry!

If you want to try to redo the port, I can send you the original source. I fork the sources and create the manifest by using the "mun" remote. But you could possibly use the original source if you don't use the remote. I don't 100% know though.

**Comment by bscheith** [comment]
No problem, thanks for the update!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by WolfLink115** [comment]
Here are the sources. 

Device:
1. https://github.com/messi2050/android_device_lge_ph2n
2. https://github.com/messi2050/android_device_lge_msm8937-common

Kernel:
1. https://github.com/messi2050/android_kernel_lge_msm8937

Vendor:
1. https://github.com/messi2050/android_vendor_lge_ph2n

Thanks!

**Comment by WolfLink115** [comment]
Closing now. Thanks for your time.
