### ISSUE TITLE
[device-port] [douglas] Amazon Fire HD 8 2017

### ISSUE THREAD

**Issue by Alee14** [Halium/projectmanagement#223]
Tree: halium-5.1

- [x] Create manifest (https://gist.github.com/Alee14/7f7c11bde039bb01da72ffd8bc1c63aa)
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by proximo-kg** [comment]
any update on this? I can't seem to use this manifest

**Comment by Alee14** [comment]
As of right now, @proximo-kg is currently going to try to help with this port

**Comment by Alee14** [comment]
Also note that the original douglas device/vendor tree repo has been relocated, ~~but the kernel repo has been deleted~~
(As of right now, I am recreating the repos)

Edit: Seems like the kernel repo still exists, but under a new name
