### ISSUE TITLE
[bullhead] Compilation is not successful on a clean sync

### ISSUE THREAD

**Issue by UniversalSuperBox** [Halium/projectmanagement#23]
The Vendor image for the Nexus 5X includes some apps that cannot be built in the Halium build system due to the lack of Java utilities. Every developer is required to comment out everything in `vendor/lge/bullhead/Android.mk`

I'll be thinking out loud for the remainder of this message.

Maybe it's possible to explicitly ignore vendor/lge/bullhead/Android.mk in the device files somehow. It might also be possible to ignore `LOCAL_MODULE_CLASS := APPS` globablly to solve this problem for any device that builds apps with stuff in vendor/.

**Comment by Flohack74** [comment]
I have a similar issue with one of my test builds but its not in vendor if I remember. Thats unfortunate since it means we have to also fork vendor trees. Until now I could always just take them from TheMuppets etc.

**Comment by vanyasem** [comment]
Simmilar issue on HTC 10 (PME). I'm thinking of writing a simple bash script that would do it, but that doesn't seem like a permanent solution

**Comment by LNJ2** [comment]
If you remove all APKs and JARs from `proprietary-files.txt` in your device tree (device and common-device), then halium-devices will automatically regenerate the vendor makefiles and fix this problem.
