### ISSUE TITLE
[device-port] [halium-10.0] [blueline] Google Pixel 3

### ISSUE THREAD

**Issue by eeeple** [Halium/projectmanagement#242]
Tree: 

- [ ] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

Based on Lineage 17.1 for crosshatch

**Comment by cybik** [comment]
Any news on this?

**Comment by LocalOracularBunny** [comment]
I have a pixel 3 I can test on if anyone more experienced can get a build to test before I manage to get one to try.

**Comment by daudix** [comment]
I'm a pixel 3 user, can we collaorate to make this & droidian work?

**Comment by eeeple** [comment]
Sorry y'all, I don't have the phone anymore nor the time (newborn isn't helping...) and porting was (from what I recall) pretty difficult.
