### ISSUE TITLE
[device-port] [halium-11.0] [renoir] Xiaomi Mi 11 Lite 5G

### ISSUE THREAD

**Issue by chmcax** [Halium/projectmanagement#280]
- Tree: [halium-11.0](https://github.com/Halium/android/tree/halium-11.0)

- [x] Create manifest [Manifest](https://github.com/Halium/halium-devices/pull/327)
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

Cannot build boot image because of [this](https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools). The system image builds correctly.

**Comment by Saikatsaha1996** [comment]
> * Tree: [halium-11.0](https://github.com/Halium/android/tree/halium-11.0)
> * [x]  Create manifest [Manifest](https://github.com/Halium/halium-devices/pull/327)
> * [ ]  Boot image and system image build successfully
> * [ ]  Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
> * [ ]  LXC container starts and does not crash
> * [ ]  libhybris tests
>   
>   * [ ]  test_gps
>   * [ ]  test_hwcomposer
>   * [ ]  test_lights
>   * [ ]  test_vibrator
>   * [ ]  test_wifi
>   * [ ]  test_sensors
>   * [ ]  test_audio
>   * [ ]  test_camera
>   * [ ]  test_input
>   * [ ]  test_nfc
>   * [ ]  test_recorder
> 
> Cannot build boot image because of [this](https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools). The system image builds correctly.

I want also port to halium -11 to my device
But I can't find check_kernel_config
and can't find halium.mk file in under build directory.. 

Need some guidance please i hope you will help me..
Waiting for your response 🙂

Thank you advance

**Comment by chmcax** [comment]
> 
> I want also port to halium -11 to my device But I can't find check_kernel_config and can't find halium.mk file in under build directory..
> 
> Need some guidance please i hope you will help me.. Waiting for your response slightly_smiling_face
> 
> Thank you advance

Hello! The halium-11 manifest does not include the halium-boot repository. I cloned the [halium-boot](https://github.com/Halium/halium-boot/tree/halium-9.0) repository to halium/halium-boot but you can't build the boot image because [get-initrd.sh](https://github.com/Halium/halium-boot/blob/master/get-initrd.sh) uses curl and the build crashes because of [this](https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools).

**Comment by Saikatsaha1996** [comment]
> > I want also port to halium -11 to my device But I can't find check_kernel_config and can't find halium.mk file in under build directory..
> > Need some guidance please i hope you will help me.. Waiting for your response slightly_smiling_face
> > Thank you advance
> 
> Hello! The halium-11 manifest does not include the halium-boot repository. I cloned the [halium-boot](https://github.com/Halium/halium-boot/tree/halium-9.0) repository to halium/halium-boot but you can't build the boot image because [get-initrd.sh](https://github.com/Halium/halium-boot/blob/master/get-initrd.sh) uses curl and the build crashes because of [this](https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools).

Yes i am doing same and build crashed also.. i don't know how to build halium-boot img another method..
My device lineage os version 18.1
Any other options available for build halium-boot img? Or port to Ubuntu touch ?

**Comment by chmcax** [comment]
> Yes i am doing same and build crashed also.. i don't know how to build halium-boot img another method..
> My device lineage os version 18.1
> Any other options available for build halium-boot img? Or port to Ubuntu touch ?

Hello! AFAIK Every Android 11 device with an Ubuntu Touch port uses the [`Standalone kernel`](https://docs.ubports.com/en/latest/porting/build_and_boot/H9_gitlab_build.html) method.

**Comment by Saikatsaha1996** [comment]
> > Yes i am doing same and build crashed also.. i don't know how to build halium-boot img another method..
> > My device lineage os version 18.1
> > Any other options available for build halium-boot img? Or port to Ubuntu touch ?
> 
> Hello! AFAIK Every Android 11 device with an Ubuntu Touch port uses the [`Standalone kernel`](https://docs.ubports.com/en/latest/porting/build_and_boot/H9_gitlab_build.html) method.

Yes but i have lineage os source code
And Standalone kernel method support halium - 11 ?

**Comment by Saikatsaha1996** [comment]
> > > Yes i am doing same and build crashed also.. i don't know how to build halium-boot img another method..
> > > My device lineage os version 18.1
> > > Any other options available for build halium-boot img? Or port to Ubuntu touch ?
> > 
> > 
> > Hello! AFAIK Every Android 11 device with an Ubuntu Touch port uses the [`Standalone kernel`](https://docs.ubports.com/en/latest/porting/build_and_boot/H9_gitlab_build.html) method.
> 
> Yes but i have lineage os source code  
I found it..
