### ISSUE TITLE
[hybris-boot] Use busybox mdev to create /dev/disk/by-name/

### ISSUE THREAD

**Issue by JBBgameich** [Halium/projectmanagement#39]
One of the reasons why Ubports still uses ubports-boot rather than hybris-boot seems to be the missing /dev/disk/by-name symlinks. While they use udev, I thought about using the busybox builtin for that as it's already included anyway. Any thoughts?

**Comment by theimpulson** [comment]
Sounds fine to me. Have you tested it ?

**Comment by LNJ2** [comment]
mdev can't generate a by-name tree. I've written a small shell script that will do the job, unfortunately it's rather slow ...
https://gist.github.com/LNJ2/848e8456e9473c157144c113a89b6139

**Comment by LNJ2** [comment]
Could someone test this? - I'm not sure if it really works (with all devices)
https://github.com/Halium/hybris-boot/pull/38

**Comment by LNJ2** [comment]
I think we can close this, because in the new initrd udev will be included and mdev definitely can't handle this.
