### ISSUE TITLE
Building systemimage sometimes freezes at making initramfs

### ISSUE THREAD

**Issue by LNJ2** [Halium/projectmanagement#46]
If I just do `mka hybris-boot` and `systemimage` on a clean checkout, in many cases it just sticks at "Making initramfs". If I press Ctrl+C and restart the build everything works fine (making initramfs takes only 1-2 s).

If we want to build the images on a CI, that's a real problem.

**Comment by z3ntu** [comment]
I didn't get any freezes last June on my CI so it was introduced since then most likely.

**Comment by LNJ2** [comment]
I tested it with travis-ci and it gave no output after 10 min, so the build was canceled. Thus, I thought it was freezing. So actually everything is working just fine.
