### ISSUE TITLE
[device-port] [wt88047] Port to Xiaomi Redmi 2/Prime [arm][5.1]

### ISSUE THREAD

**Issue by abhishek9650** [Halium/projectmanagement#49]
HALIUM PORT FOR WT88047 BASED ON CM12.1

manifest : https://gist.github.com/abhishek9650/40cc176b8279aa393a11281522a3354f

**Comment by LNJ2** [comment]
And I don't think you need two issues for one device, even if it uses 5.1 and 7.1 you can add all information collected under one issue.

**Comment by abhishek9650** [comment]
i have to. mount points are different.. and i think i will make arm64 based images instead of regular arm.. so a new issue is needed

**Comment by bhush9** [comment]
You didn't get point, even if there is different rootfs, device itself is single one.. so I am closing this issue, please consolidate information in your original issue.
