### ISSUE TITLE
[device-port] [land] Xiaomi Redmi 3S/Prime/3X

### ISSUE THREAD

**Issue by rupansh** [Halium/projectmanagement#80]
Tree: halium-7.1
Note- Everything will be tested on "Prime" Variant.
- [x] Create manifest: https://github.com/Halium/halium-devices/pull/92
- [x] Boot image and system image build successfully
- [x] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [x] LXC container starts and does not crash
- [ ] libhybris tests
  * [x] test_gps
  * [x] test_hwcomposer
  * [x] test_lights
  * [x] test_vibrator
  * [ ] test_wifi
  * [x] test_sensors
  * [x] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc (Not applicable as there is no NFC sensor)
  * [ ] test_recorder

**Comment by ghost** [comment]
you stopped porting?

**Comment by rupansh** [comment]
@AVICEBLACK currently, its on halt as it is working fine for all the Rootfs excluding UBports which has broken CAF support.

**Comment by rupansh** [comment]
Temporarily abandoned by me. @SRIDHARDV is continuing the development
@vanyasem you may change the asignee for now.

**Comment by SRIDHARDV** [comment]
I'm continue porting for this device. But since @rupansh has started the porting, @vanyasem if possible assign for both.

**Comment by vanyasem** [comment]
I cannot assign you to this issue because you're not it's creator and not a member of the org. @SRIDHARDV

**Comment by doniks** [comment]
But of course you don't need to be assigned to work on the port :)

**Comment by kskarthik** [comment]
@rupansh @SRIDHARDV any update on this? I have a land device! What are the hurdles present to make ubuntu touch workable?

**Comment by SRIDHARDV** [comment]
> @rupansh @SRIDHARDV any update on this? I have a land device! What are the hurdles present to make ubuntu touch workable?

@kskarthik  Currently i didn't have my land device, but Ubuntu Touch is working with my Repo, there is some common problem like no Audio and Call. Display, touch, SIM card, SMS are working give it a try. if you had time please contribute to Ubuntu Touch as well, Use Telegram app for getting community support.

**Comment by kskarthik** [comment]
@SRIDHARDV thank you for the info! I am intented to port ubuntu touch to it. Can you please link me ubports telegram group. Also, I'm new to ubuntu porting. I am familiar with sailfish & postmarketOS porting previously. Can you help me with getting familiar?

**Comment by kskarthik** [comment]
@SRIDHARDV `<project path="vendor/xiaomi" name="proprietary_vendor_xiaomi" remote="them" />`

TheMuppets repo doesn't have proprietary vendor xiaomi now :/ what to do ?

**Comment by doniks** [comment]
does this https://github.com/Halium/android/commit/6327909e621b843f25bbfdc4c093b10afcdeb530 help?

**Comment by kskarthik** [comment]
@doniks it should help. Thanks! Forked it on my gitlab acc for archiving purpose.
