### ISSUE TITLE
[device-port] [a106] Micromax Unite2 

### ISSUE THREAD

**Issue by heyrudra** [Halium/projectmanagement#94]
Tree: halium-7.1

- [x] Create manifest 
- [x] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by doniks** [comment]
if you have a manifest, please reopen and link it

**Comment by lnjX** [comment]
@doniks Thanks for doing this stuff :)
